### ISSUE TITLE
Group page freezing

### ISSUE THREAD

**Issue by lk-minot** [vCarbonnn/TagProGroupChatNotifier#1]
When i'm on a group and that i drag and drop a player name in a column it freeze the tab.
![Screenshot](http://i.imgur.com/9pJtAmQ.png)

I'm runing this script under Chromium 46.0.2490.71 with the extension Tampermonkey 3.12 on a Debian testing 64-bit.

Any idea where's the problem come from ?

**Comment by vCarbonnn** [comment]
Could you try v1.6.1 and see if the issue is resolved?

**Comment by lk-minot** [comment]
Thank you it seem resolved, great job !
